- type: job
  id: MedicalDoctor
  name: job-name-doctor
  playTimeTracker: JobMedicalDoctor
  startingGear: DoctorGear
  icon: "MedicalDoctor"
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: MedicalIDCard
    belt: ClothingBeltMedicalFilled
    pocket1: RadioHandheld
    pocket2: SpaceCash20
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
