- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "Psychologist"
  supervisors: job-supervisors-cmo
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 4800
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesLeather
    id: PsychologistIDCard
  innerclothingskirt: ClothingUniformJumpsuitPsychologist
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
