- type: job
  id: FrigidSoldier
  name: job-name-soldier
  playTimeTracker: JobSoldier
  startingGear: SoldierGear
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000
  icon: "Soldier"
  canBeAntag: false
  accessGroups:
    - AllAccess

- type: startingGear
  id: SoldierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitary
    back: WeaponRifleLecter
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerclothing: ClothingOuterVestKevlar
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltSecurityWebbing
    pocket1: BaseMagazineRifle
    pocket2: BaseMagazineRifle
