- type: job
  id: SecurityCadet
  name: job-name-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1800
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig

- type: startingGear
  id: SecurityCadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPolice
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    id: SecurityCadetIDCard
  innerclothingskirt: ClothingUniformJumpsuitPolice
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
