- type: job
  id: StationEngineer
  name: job-name-engineer
  playTimeTracker: JobStationEngineer
  startingGear: StationEngineerGear
  icon: "StationEngineer"
  access:
  - Engineering

- type: startingGear
  id: StationEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterVestHazard
    id: EngineeringIDCard
    belt: ClothingBeltElectricalFilled
    gloves: ClothingHandsGlovesColorYellow
  innerclothingskirt: ClothingUniformJumpskirtEngineering
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
