- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  roles:
  - Chef
  - Civilian
  - Botanist
  - Chaplain
  - Prisoner
  - Reporter
  - Bartender
  - ServiceWorker

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - StationEngineer
  - Mechanic

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - MedicalDoctor
  - MedicalIntern

- type: department
  id: Security
  description: department-Command-description
  color: "#DE3A3A"
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - FrigidSoldier
  - ServiceWorker
  - Prisoner
#  - Detective
#  - Warden

#- type: department
#  id: Science
#  roles:
#  - Chemist
#  - Scientist
