- type: department
  id: Civilian
  roles:
  - Civilian

- type: department
  id: Engineering
  roles:
  - StationEngineer

- type: department
  id: Medical
  roles:
  - MedicalDoctor
  - MedicalIntern

- type: department
  id: Security
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden

- type: department
  id: Science
  roles:
  - Chemist
  - Scientist
