- type: job
  id: Chaplain
  name: job-name-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "Chaplain"
  supervisors: job-supervisors-hop
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 1800
    - !type:OverallPlaytimeRequirement
      time: 1800
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: ChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpackChaplainFilled
    shoes: ClothingShoesColorBlack
  innerclothingskirt: ClothingUniformJumpskirtChaplain
  satchel: ClothingBackpackSatchelChaplainFilled
  duffelbag: ClothingBackpackDuffelChaplainFilled
