- type: job
  id: Reporter
  name: job-name-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "Reporter"
  supervisors: job-supervisors-hop
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 1800
    - !type:OverallPlaytimeRequirement
      time: 1800
  access:
  - Service
  - Maintenance

- type: startingGear
  id: ReporterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
  innerclothingskirt: ClothingUniformJumpsuitJournalist
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
