- type: job
  id: Chemist
  name: job-name-chemist
  playTimeTracker: JobChemist
  startingGear: ChemistGear
  icon: "Chemist"
  supervisors: job-supervisors-cmo
  access:
  - Chemistry
  - Research
  special:
  - !type:AddComponentSpecial
    components:
    - type: AiFactionTag
    factions:
      - Nanotrasen

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChemistry
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLabChem
    id: ChemistryPDA
    belt: ClothingBeltMedical
    pocket1: SpaceCash30
    pocket2: RadioHandheld
    # the purple glasses?
  innerclothingskirt: ClothingUniformJumpskirtChemistry
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
