- type: job
  id: Scientist
  name: job-name-scientist
  playTimeTracker: JobScientist
  startingGear: ScientistGear
  icon: "Scientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  special:
  - !type:AddComponentSpecial
    components:
    - type: AiFactionTag
    factions:
      - Nanotrasen

- type: startingGear
  id: ScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
    pocket1: RadioHandheld
    pocket2: SpaceCash30
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
