- type: job
  id: Scientist
  name: job-name-scientist
  playTimeTracker: JobScientist
  startingGear: ScientistGear
  icon: "Scientist"
  supervisors: job-supervisors-rd
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 4800
  access:
  - Research

- type: startingGear
  id: ScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
    pocket1: RadioHandheld
    pocket2: SpaceCash30
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
